version: '3.6'
services:
  engine-metadata-db:
    image: postgres:12
    restart: always
    container_name: 'engine-metadata-db'
    volumes:
      - metadata_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:dev-8f86ee6-main.ubuntu.arm64
    ports:
      - '8080:8080'
    depends_on:
      - 'engine-metadata-db'
    restart: always
    container_name: 'graphql-engine'
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@engine-metadata-db:5432/postgres
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgresql://postgres:test@host.docker.internal:6001/chinook
      MSSQL_DATABASE_URL: "'Driver={ODBC Driver 17 for SQL Server};Server=tcp:host.docker.internal,1433;Database=bikes;Uid=sa;Pwd=Oftw4321@;'"
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: 'naming_convention'
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: moocow
volumes:
  metadata_db_data:
networks:
  default:
    name: HASURA_DEV_NETWORK
    external: true
